SELECT * FROM customer_behavior.sales;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) AS Total_revenue
FROM sales
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount FROM sales
WHERE purchase_amount>
(SELECT AVG(purchase_amount) FROM sales) and discount_applied="Yes";

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,ROUND(AVG(review_rating),2) AS avg_review_rating
FROM sales
GROUP BY 1
ORDER BY 2 DESC LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,ROUND(AVG(purchase_amount),2) AS total_revenue
FROM sales
WHERE shipping_type IN ("Express","Standard")
GROUP BY 1;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,ROUND(AVG(purchase_amount),2) AS avg_spend,SUM(purchase_amount) AS total_revenue
FROM sales
GROUP BY 1;

-- Q6. Which 5 products have the highest percentage of purchases withdiscounts applied?
SELECT item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied="Yes" THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM sales
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal basedontheir totalnumber of previous purchases, and show the count of each segment.
WITH cte AS (
SELECT customer_id,
CASE 
  WHEN previous_purchases=1 THEN "New"
  WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
  ELSE "Loyal"
END as customer_type
FROM sales)

SELECT customer_type,COUNT(*) AS no_of_each_type_customer
FROM cte 
GROUP BY 1;

-- Q8. What are the top 3 most purchased products within each category?
WITH cte AS(
SELECT category,item_purchased,COUNT(customer_id) AS total_order,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM sales
GROUP BY 1,2)

SELECT category,item_purchased,total_order
FROM cte
WHERE item_rank<=3;

-- Q9. Are customers who are repeated buyers (more than 5 previous purchasesyalso- likely to subscribe?
SELECT subscription_status,COUNT(customer_id) AS repeat_buyers
FROM sales
WHERE previous_purchases>=5
GROUP BY 1;


-- Q1O. What is the revenue contribution of each age group
SELECT age_group,SUM(purchase_amount) AS Total_revenue
FROM sales
GROUP BY 1
ORDER BY 2 DESC;



